### ISSUE TITLE
Tests fail when run in parallel

### ISSUE THREAD

**Issue by hillu** [libyal/libsmraw#1]
Hi,

I ran into problems while preparing a package for inclusion in Debian: When running tests in parallel, there are failures. Apparently the hard-coded tmp directory is removed by one instance while another is accessing it.

<pre>
=============================================
   libsmraw 20150105: tests/test-suite.log
=============================================

# TOTAL: 6
# PASS:  2
# SKIP:  4
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

SKIP: test_open_close.sh
========================

No input directory found.
SKIP test_open_close.sh (exit status: 77)

SKIP: test_seek.sh
==================

No input directory found.
SKIP test_seek.sh (exit status: 77)

SKIP: test_read.sh
==================

No input directory found.
SKIP test_read.sh (exit status: 77)

SKIP: test_smrawverify.sh
=========================

No input directory found.
SKIP test_smrawverify.sh (exit status: 77)
</pre>

**Comment by joachimmetz** [comment]
I'll have a look to change the tmp directory to something more unique

**Comment by joachimmetz** [comment]
> Apparently the hard-coded tmp directory is removed by one instance while another is accessing it.

Made some changes to the test scripts, let me know if that works for you.

`No input directory found.`

However in your output is seems you don't have an input directory defined. Also see: https://github.com/libyal/libsmraw/wiki/Testing#test-files

**Comment by joachimmetz** [comment]
No feedback from OP, assuming works now, closing issue.

**Comment by hillu** [comment]
Sorry, I didn't notice your last comments. Just tested -- everything seems to be okay now.

**Comment by joachimmetz** [comment]
> Sorry, I didn't notice your last comments. Just tested -- everything seems to be okay now.

No worries, the comment is to indicate the status; the issue can be reopened if needed. 
Largely that I do not let open and fixed issues linger too long ;)
