### ISSUE TITLE
tests fail due to missing files

### ISSUE THREAD

**Issue by hillu** [libyal/libsmraw#2]
Hi,

https://github.com/libyal/libsmraw/releases/download/20170715/libsmraw-alpha-20170715.tar.gz is missing the following files

- tests/smraw_test_libbfio.h
- tests/smraw_test_libcsystem.h
- tests/smraw_test_libcthreads.h

I had to add those from the git master branch to be able to build the Debian package.

**Comment by joachimmetz** [comment]
released version 20170802: https://github.com/libyal/libsmraw/releases/tag/20170802

this should contain the necessary changes

**Comment by joachimmetz** [comment]
Test are failing on launchpad for me: https://launchpadlibrarian.net/331587757/buildlog_ubuntu-xenial-amd64.libsmraw_20170802-1ppa1~xenial_BUILDING.txt.gz

Will look into this when time permits, might need to disable them for now

**Comment by hillu** [comment]
@joachimmetz My package in Debian contains the patch mentioned in #3. Without that patch, building using _sbuild_ fails with the same symptoms. The _sbuild_ build log tell me that the build directory ends with `build/libsmraw-vsnO6p/libsmraw-20170802`.

**Comment by joachimmetz** [comment]
Current hypothesis, this is because I did not update all the test scripts.

To quote Homer Simpson "D'oh!"
